apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # tls:
  #   - hosts:
  #       - dummy.io
  #     secretName: dummy-tls
  rules:
    - host: dummy.io
      http:
        paths:
          - path: /
            backend:
              serviceName: dummy-service
              servicePort: 3000
